### ISSUE TITLE
error while using ./run-bagdump.sh

### ISSUE THREAD

**Issue by sourav-roni** [rwightman/udacity-driving-reader#10]
File "/usr/local/lib/python2.7/dist-packages/pandas/compat/__init__.py", line 421, in <module>
    raise ImportError('dateutil 2.5.0 is the minimum required version')
ImportError: dateutil 2.5.0 is the minimum required version

I have dateutil version 2.7 yet its giving the error.

**Comment by dd292** [comment]
Hey I am having the same problem. Did you find a solution?

**Comment by sourav-roni** [comment]
Yeah just posted the docker file in the new issue, check it out.
