### ISSUE TITLE
Issue while extracting the data

### ISSUE THREAD

**Issue by dd292** [rwightman/udacity-driving-reader#11]
Hey,

Thanks a lot for the data set.

I am having a issue,  when I try to use the bagdump.sh it is giving an error
File "/usr/local/lib/python2.7/dist-packages/pandas/compat/__init__.py", line 421, in <module>
    raise ImportError('dateutil 2.5.0 is the minimum required version')
ImportError: dateutil 2.5.0 is the minimum required version

Do you have any idea why this might be happening.

Thanks

**Comment by sourav-roni** [comment]
Hi, I added dateutil to be installed explicitly.

Here is the updated docker file:
(Note : remove the .txt extension) :) 
--------------------------------------------------------------------------------------------------------------------------------

[Dockerfile.txt](https://github.com/rwightman/udacity-driving-reader/files/2029802/Dockerfile.txt)

**Comment by dd292** [comment]
Hey it worked thanks man.!
