### ISSUE TITLE
error ./run.sh: line 32: docker: command not found

### ISSUE THREAD

**Issue by NamDinhRobotics** [rwightman/udacity-driving-reader#12]
Hi!
I tried to run ./run-bagdump.sh -i /data -o /output , but got the error
 ./run.sh: line 32: docker: command not found
I set my folders follow this image,
please help me!!
![screenshot from 2018-05-25 19-18-35](https://user-images.githubusercontent.com/30413547/40539740-ac72604a-6050-11e8-951a-be9f3b6e6e63.png)

**Comment by rwightman** [comment]
Looks like you probably used relative paths, the paths get passed through to Docker volume mappings and those need to be absolute ... ie /home/DataDeep/Ch2_001/output not ./output

**Comment by JiweiTian** [comment]
I encounterd this problem also. The absolute path also don't work! Can you help me ?

**Comment by JiweiTian** [comment]
@NamDinhRobotics @rwightman @RunOrVeith I encounterd this problem also. The absolute path also don't work! Can you help me ?
