### ISSUE TITLE
./run.sh: line 32: docker: command not found

### ISSUE THREAD

**Issue by xeron56** [rwightman/udacity-driving-reader#13]
```

root@bf9f40921c8d:/dataset/udacity-driving-reader-master# ./run-bagdump.sh -i /dataset/udacity-driving-reader-master/data -o /dataset/udacity-driving-reader-master/output

Running 'python script/bagdump.py' with input dir '/dataset/udacity-driving-reader-master/data', output dir '/dataset/udacity-driving-reader-master/output', docker image 'udacityreader'...

./run.sh: line 32: docker: command not found

root@bf9f40921c8d:/dataset/udacity-driving-reader-master#


```
![kah](https://user-images.githubusercontent.com/11449967/42734908-86e473e6-886d-11e8-9191-a5653314424f.JPG)

**Comment by xeron56** [comment]
Duplicate of #12

**Comment by JiweiTian** [comment]
I encounterd this problem also. The absolute path also don't work! Can you help me ?

**Comment by JiweiTian** [comment]
@shahidul56 @RunOrVeith @rwightman I encounterd this problem also. The absolute path also don't work! Can you help me ?

**Comment by xeron56** [comment]
```
INPUT_DIR="/data/"

OUTPUT_DIR="/data/output"


```
Change this part as full path /absolute path like , say your folder is on desktop 

```
INPUT_DIR="/home/[myfolder name]/[mysubfolder name]/data/"

OUTPUT_DIR="/home/[myfolder name]/[sub folder name]/data/output"

```

**Comment by JiweiTian** [comment]
Thank you for your suggestion.@shahidul56 
I did as you suggested as shown in the attached figure. It also don't work! I don't know why 
![捕获](https://user-images.githubusercontent.com/45908316/57532056-7dc1e780-736d-11e9-8671-3afcd2b898e6.PNG)
?
