### ISSUE TITLE
Timestamps from interpolated.csv not existing in brake.csv

### ISSUE THREAD

**Issue by mirunabarbu** [rwightman/udacity-driving-reader#16]
Hi!

I used this reader to convert the dataset for Udacity challenge 2 from .bag files to images and .csv files, but the timestamps in the break.csv do not correspond either to the ones in the interpolated.csv nor to the images filenames ([link ](https://drive.google.com/open?id=1SuLmIcBDC13ReqmZeqhIj57dNNHBKd2q) to the 2 files). This also happens for timestamps in the gear.csv or gps.csv. As it was recommended in the repository readme, I used [this](https://github.com/rwightman/udacity-driving-reader/blob/master/script/bagdump.py) script. 

Do you know why this may happen? or how can I correlate the timestamps in brake.csv, for instance with the images?

Thanks,
Miruna

**Comment by rwightman** [comment]
It would be straight forward to interpolate any of the other sensors if you desired.

If you look at the code, none of the sensors that I termed 'others' are currently interpolated. They were not necessary for the original challenge and I never interpolated their output. For each sensor, including the GPS, the validity of their linear interpolated result is up for debate. At small enough time scales it is usually 'good enough'. The brake specifically might not make sense though, I don't recall the scale/units.
