### ISSUE TITLE
Issues related to Dockerfile and run.sh

### ISSUE THREAD

**Issue by aayushARM** [rwightman/udacity-driving-reader#17]
There were several issues I faced while trying to extract the data from .bag files:
Docker file:
When trying to run as is:
- pandas throws errors stating numpy version is 11.5.0, while >=12.0.0 is needed.
- Similarly, several other PyPi packages that are already installed in ros:kinetic-vision image are left as older versions since there's no --upgrade flag at the end of pip commands(ex. PyYaml, numpy, matplotlib, ipykernel, python-dateutil), which causes problems.

Run.sh:
- Doesn't do anything for me since Docker expects absolute paths for OUTPUT_DIR and INPUT_DIR, while given paths are relative to current directory.

After fixing the above problems, everything works as expected. I think Docker file and Run.sh need small changes. I have opened a pull request, please have a look.

**Comment by rwightman** [comment]
Thanks for the PR, haven't had a chance to run so will leave open for now so others can find it. This project is getting a bit dated, hence the python package version issues, upgrade as you suggest helps. Overall someone should/could update everything to use Melodic :)

The paths in run.sh are already absolute, they lead with a slash, they just reference a specific location for the data that's not in the current directory. One way or another what needs to go there is system specific, perhaps in pwd is a bit more generic for a default but not critical either way, the user has to understand it needs to match the location of data folder on their system.

**Comment by rwightman** [comment]
All fixed, thanks
