### ISSUE TITLE
 error ./run.sh: line 32: docker: command not found 

### ISSUE THREAD

**Issue by JiweiTian** [rwightman/udacity-driving-reader#19]
https://github.com/rwightman/udacity-driving-reader/issues/12
The absolute path also don't work!
Can you help me?
Thank you very much!

**Comment by rwightman** [comment]
I just did a quick test after updating the dockerfile based on @aayushARM work, everything works fun with the bag file extraction still. Again make sure both your input and output paths are definitely absolute (from the root of your filesystem). Make sure there are bag files to be found in the input folder and that you have the correct read and write permissions in the input and output folder (respectively). Also make sure you build the docker image first.

**Comment by JiweiTian** [comment]
Thanks for your reply. The above issue is solved. However, i encountered the following issue. In fact, i have numpy==1.13.0 on the host and the container. So i don't know why it still don't work. Can you help me？ Thank  you.  @rwightman 
![图片](https://user-images.githubusercontent.com/45908316/57569665-defbc080-742a-11e9-9a9a-aa857b60e24f.png)

**Comment by rwightman** [comment]
Try updating to the latest commit of this repo, rebuild the container.
