### ISSUE TITLE
error in run-bagdump.sh

### ISSUE THREAD

**Issue by YihaoX** [rwightman/udacity-driving-reader#20]
this is that in my terminal, could someone help me please...

```
root@MONTO:/mnt/j/ucity/udacity-driving-reader-master# ./run-bagdump.sh -i /mnt/j/ucity -o /mnt/j/ucity/data
Running 'python script/bagdump.py' with input dir '/mnt/j/ucity', output dir '/mnt/j/ucity/data', docker image 'udacity-reader'...
python: can't open file 'script/bagdump.py': [Errno 2] No such file or directory
```

thanks!

**Comment by rwightman** [comment]
I did a build.sh and run-bagdump.sh, docker version 18.09.07 from clean checkout and cannot reproduce. If you run just ./run.sh and look at the folder structure in the container, the 'script' folder should contain some python scripts. If it doesn't, something wrong with your build. Remove container, try run build.sh again. Make sure your docker is setup correctly, etc.
