### ISSUE TITLE
Any advice on how to use the script in windows?

### ISSUE THREAD

**Issue by tyluckyma** [rwightman/udacity-driving-reader#4]
Hi thanks for your nice script.

Howeer, I'm trying to run the script in windows 10, any structions on how to do so? How about directly run the ./build.sh in powershell? And then run the ./run-bagdump.sh command?

In addition, I'm new to this docker thing. Can you please briefly specify how to "Build the docker container manually"

Or a simpler way, may I ask is there any way I can download the extracted image files and csv files?

**Comment by rwightman** [comment]
It should run in Windows within a VM.
