### ISSUE TITLE
Dumping rosbag data inquiry 

### ISSUE THREAD

**Issue by benn94** [rwightman/udacity-driving-reader#5]
I am new to docker and I have tried reading and watching tutorials on the internet for a while, but it's not helpful. I wonder how I should run the script files within the Container. Am I supposed to copy this reader directory to a container so that I can run the script files ?

**Comment by rwightman** [comment]
As per the documentation in the 'Usage' section of the readme. You can use the provided build and run shell scripts to execute the script files within the container without knowing much about Docker. Build takes care of building the container using the included Dockerfile.

**Comment by benn94** [comment]
I keep running into the problem below even though I have copied the reader directory to the container just to run the shell script.

```
root@081e3018b6de:/udacity-driving-reader# ./run-bagdump.sh -i /data -o /output
Running 'python script/bagdump.py' with input dir '/data', output dir '/output', docker image 'udacity-reader'...
./run.sh: line 32: docker: command not found
```

**Comment by rwightman** [comment]
What's the output of the command 'docker info' for the 'Server Version' and 'Operating System' fields?

**Comment by benn94** [comment]
`Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.761 GiB
Name: borinyun-com
ID: PGV7:7DRH:2NRC:LZB7:TXGG:HK5L:W736:YVXK:R5VC:27D6:GYEO:YWN4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false
`

**Comment by benn94** [comment]
This is the output

```
Containers: 1
 Running: 1
 Paused: 0
 Stopped: 0
Images: 5
Server Version: 17.03.1-ce
Storage Driver: aufs
 Root Dir: /var/lib/docker/aufs
 Backing Filesystem: extfs
 Dirs: 18
 Dirperm1 Supported: true
Logging Driver: json-file
Cgroup Driver: cgroupfs
Plugins: 
 Volume: local
 Network: bridge host macvlan null overlay
Swarm: inactive
Runtimes: runc
Default Runtime: runc
Init Binary: docker-init
containerd version: 4ab9917febca54791c5f071a9d1f404867857fcc
runc version: 54296cf40ad8143b62dbcaa1d90e520a2136ddfe
init version: 949e6fa
Security Options:
 apparmor
 seccomp
  Profile: default
Kernel Version: 4.4.0-79-generic
Operating System: Ubuntu 16.04.2 LTS
OSType: linux
Architecture: x86_64
CPUs: 4
Total Memory: 7.761 GiB
Name: borinyun-com
ID: PGV7:7DRH:2NRC:LZB7:TXGG:HK5L:W736:YVXK:R5VC:27D6:GYEO:YWN4
Docker Root Dir: /var/lib/docker
Debug Mode (client): false
Debug Mode (server): false
Registry: https://index.docker.io/v1/
WARNING: No swap limit support
Experimental: false
Insecure Registries:
 127.0.0.0/8
Live Restore Enabled: false

```

**Comment by rwightman** [comment]
I just noticed from your prompt, it looks like you're running the bagdump.sh within a docker container? It's supposed to be run from your host system to execute the script within the docker environment.

**Comment by benn94** [comment]
Before trying the shell scrip inside the container, i have tried running the script in the host system. But I have not seen any output file or output folder.

here is my dir
```
/udacity-driving-reader$ ls 
build.sh  Dockerfile   README.md      run-bagdump.sh  script
data      LICENSE.txt  run-bag2tf.sh  run.sh
/udacity-driving-reader$ cd data/
/udacity-driving-reader/data$ ls
Ch2_002
/udacity-driving-reader/data$ cd Ch2_002/
/udacity-driving-reader/data/Ch2_002$ ls
HMB_1.bag  HMB_2.bag  HMB_4.bag  HMB_5.bag  HMB_6.bag  HMB.txt
```
This is when I run `./run-bagdump.sh -i /data -o /output`
```
/udacity-driving-reader$ sudo ./run-bagdump.sh -i /data -o /output
Running 'python script/bagdump.py' with input dir '/data', output dir '/output', docker image 'udacity-reader'...
```
So I check my dir again
```
/udacity-driving-reader$ cd data/
/udacity-driving-reader/data$ ls
Ch2_002
/udacity-driving-reader/data$ cd Ch2_002/
/udacity-driving-reader/data/Ch2_002$ ls 
HMB_1.bag  HMB_2.bag  HMB_4.bag  HMB_5.bag  HMB_6.bag  HMB.txt
```

**Comment by rwightman** [comment]
The -i and -o arguments have to point to the absolute paths of the host system where your input bag files reside and your output is to go, they get mapped to /data and /output within the container. It looks  like your data is in /udacity-driving-reader/data/Ch2_002 so you'd need to specify that as the -i argument. Docker is not very good at providing meaningful errors if you specify invalid path mappings.
