### ISSUE TITLE
Dumping all the data is rosbag to csv

### ISSUE THREAD

**Issue by swarnakr** [rwightman/udacity-driving-reader#6]
Hi,

Thanks for the dataset reader code. 

I'm interested in extracting point correspondence between consecutive images in the dataset. I'm interested in 3D points present in sensor_msgs/PointCloud2 and the extrinsic camera parameters in either sensor_msgs/JointState or tf2_msgs/TFMessage.

Could you please provide a more generic code that can extract this data into csv files too?

Many thanks.

**Comment by rwightman** [comment]
I have on plans to revisit this code at present time. I don't imagine it will be too difficult to add support for different topics with different msg types. I do freelance work if it's important to you.
