### ISSUE TITLE
Requirements to run the scripts?

### ISSUE THREAD

**Issue by ghost** [rwightman/udacity-driving-reader#8]
Hello there,
was wondering if there are many machine specs required to run the script? because I'm trying to run it on a large dataset (80 GBs) and it's stuck at processing dataset, never making any progress or writing any images and it causes my ubuntu to freeze.
Thanks

**Comment by rwightman** [comment]
I have no idea what the specific reqs are, but the process of just opening the bag file can take a very long time with huge bag files that have lots of entries. It's not the most scalable file format and the whole index of all entries is scanned and parsed whenever you open it. I've seen this take many minutes on fast machines with SSD for very large files.
