### ISSUE TITLE
Accessing velodyne packets

### ISSUE THREAD

**Issue by colloquialdamage** [rwightman/udacity-driving-reader#9]
The script doesn't extract Velodyne packets/data from the .bag file. While the yaml shows inclusion of the following topic: /velodyne_packets, the topic is not accessed via the script.
Can you please add that?

**Comment by rwightman** [comment]
I thought I had some code for this somewhere else but can't find it. Shouldn't be too hard to find another example and add it in. 

Some starting point in the link below, but I do recall there being the necessity to have the driver for the Velodyne available if it's still in the binary packet format in the bag. You'd have to pass the binary data from the packet to the velodyne driver first before getting a point cloud that you can use or convert.
https://answers.ros.org/question/278052/reading-velodynescan-from-bagfile-offline/
